#!/usr/bin/env python3
"""Compare offline detection algorithms using existing virtual ECU traces.

This script reads the raw CSV files generated by Paper Study v1. It does not
run or modify the C simulator, alter CSV schemas, or interact with the GUI.
The detector implementation lives in ``virtual_ecu.detection_algorithms`` so
the GUI and offline study use the same logic.
"""

from __future__ import annotations

import argparse
import csv
import math
import os
import sys
from pathlib import Path
from typing import Dict, List, Sequence


PROJECT_ROOT = Path(__file__).resolve().parents[1]
PYTHON_PACKAGE_ROOT = PROJECT_ROOT / "python"
if str(PYTHON_PACKAGE_ROOT) not in sys.path:
    sys.path.insert(0, str(PYTHON_PACKAGE_ROOT))

from virtual_ecu.detection_algorithms import (  # noqa: E402
    CUSUM_ALLOWANCES,
    CUSUM_DECISION_LIMITS,
    EWMA_ALPHA,
    EWMA_LIMITS,
    THRESHOLD_LIMITS,
    evaluate_detection,
)


DEFAULT_INPUT_DIR = PROJECT_ROOT / "results" / "paper_study_v1" / "raw"
DEFAULT_OUTPUT_DIR = PROJECT_ROOT / "results" / "detection_study_v1"

SCENARIO_IDS = [
    "baseline",
    "fan_stuck_hot_stress",
    "pump_degraded_only",
    "stale_sensor_data_hot_stress",
    "sensor_bias_only",
    "calibration_memory_corruption",
    "paper_default_multi_fault",
]

ALGORITHM_ORDER = ["threshold", "ewma", "cusum"]
OUTPUT_COLUMNS = [
    "scenario_id",
    "algorithm",
    "fault_type",
    "fault_start_s",
    "detected",
    "first_detection_s",
    "detection_latency_s",
    "first_dtc_label_from_ecu",
    "ecu_dtc_detection_latency_s",
    "final_safe_state",
    "max_coolant_temp_c",
    "false_positive_count",
    "missed_detection",
]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Compare offline threshold, EWMA, and CUSUM detectors."
    )
    parser.add_argument(
        "--input-dir",
        type=Path,
        default=DEFAULT_INPUT_DIR,
        help="Directory containing Paper Study v1 raw CSV traces.",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=DEFAULT_OUTPUT_DIR,
        help="Directory for comparison CSV, Markdown summary, and figures.",
    )
    parser.add_argument(
        "--no-figures",
        action="store_true",
        help="Skip optional Matplotlib figures.",
    )
    return parser.parse_args()


def format_optional_float(value: object) -> str:
    return "n/a" if value is None else f"{float(value):.3f}"


def as_output_row(result: Dict[str, object]) -> Dict[str, str]:
    return {
        "scenario_id": str(result["scenario_id"]),
        "algorithm": str(result["algorithm"]),
        "fault_type": str(result["fault_type"]),
        "fault_start_s": format_optional_float(result["fault_start_s"]),
        "detected": str(int(bool(result["detected"]))),
        "first_detection_s": format_optional_float(result["first_detection_s"]),
        "detection_latency_s": format_optional_float(result["detection_latency_s"]),
        "first_dtc_label_from_ecu": str(result["first_ecu_dtc_label"]),
        "ecu_dtc_detection_latency_s": format_optional_float(
            result["ecu_dtc_latency_s"]
        ),
        "final_safe_state": str(result["final_safe_state"]),
        "max_coolant_temp_c": f"{float(result['max_coolant_temp_c']):.2f}",
        "false_positive_count": str(int(result["false_positive_count"])),
        "missed_detection": str(int(bool(result["missed_detection"]))),
    }


def run_study(input_dir: Path) -> List[Dict[str, object]]:
    results: List[Dict[str, object]] = []
    for scenario_id in SCENARIO_IDS:
        path = input_dir / f"{scenario_id}.csv"
        if not path.is_file():
            raise FileNotFoundError(f"Required raw trace not found: {path}")
        for algorithm in ALGORITHM_ORDER:
            result = evaluate_detection(path, algorithm)
            result["scenario_id"] = scenario_id
            results.append(result)
    return results


def write_comparison_csv(path: Path, results: Sequence[Dict[str, object]]) -> None:
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=OUTPUT_COLUMNS)
        writer.writeheader()
        writer.writerows(as_output_row(result) for result in results)


def algorithm_metrics(
    results: Sequence[Dict[str, object]],
) -> Dict[str, Dict[str, float | int]]:
    metrics: Dict[str, Dict[str, float | int]] = {}
    for algorithm in ALGORITHM_ORDER:
        algorithm_rows = [
            row for row in results if str(row["algorithm"]) == algorithm
        ]
        fault_rows = [
            row for row in algorithm_rows if str(row["fault_type"]) != "none"
        ]
        detected_rows = [row for row in fault_rows if bool(row["detected"])]
        latencies = [
            float(row["detection_latency_s"])
            for row in detected_rows
            if row["detection_latency_s"] is not None
        ]
        baseline_row = next(
            row for row in algorithm_rows if str(row["scenario_id"]) == "baseline"
        )
        metrics[algorithm] = {
            "fault_scenarios": len(fault_rows),
            "detected": len(detected_rows),
            "detection_rate": (
                len(detected_rows) / len(fault_rows) if fault_rows else 0.0
            ),
            "mean_latency_s": (
                sum(latencies) / len(latencies) if latencies else math.nan
            ),
            "baseline_false_positives": int(baseline_row["false_positive_count"]),
            "missed": sum(int(bool(row["missed_detection"])) for row in fault_rows),
        }
    return metrics


def write_summary(path: Path, results: Sequence[Dict[str, object]]) -> None:
    metrics = algorithm_metrics(results)
    lines = [
        "# Detection Algorithm Study v1",
        "",
        "This offline study compares residual-based detectors using the existing "
        "`results/paper_study_v1/raw/` traces. It does not alter or replace the "
        "virtual ECU diagnostic logic.",
        "",
        "## Algorithm Summary",
        "",
        "| Algorithm | Fault scenarios detected | Detection rate | Mean latency [s] | Baseline false positives | Missed detections |",
        "|---|---:|---:|---:|---:|---:|",
    ]
    for algorithm in ALGORITHM_ORDER:
        item = metrics[algorithm]
        mean_latency = item["mean_latency_s"]
        mean_text = (
            "n/a" if math.isnan(float(mean_latency)) else f"{float(mean_latency):.3f}"
        )
        lines.append(
            f"| {algorithm} | {item['detected']}/{item['fault_scenarios']} | "
            f"{100.0 * float(item['detection_rate']):.1f}% | {mean_text} | "
            f"{item['baseline_false_positives']} | {item['missed']} |"
        )

    lines.extend(
        [
            "",
            "## Detector Configuration",
            "",
            f"- Threshold limits: `{THRESHOLD_LIMITS}`.",
            f"- EWMA smoothing factor: `{EWMA_ALPHA:.2f}`; limits: `{EWMA_LIMITS}`.",
            f"- CUSUM allowances: `{CUSUM_ALLOWANCES}`.",
            f"- CUSUM decision limits: `{CUSUM_DECISION_LIMITS}`.",
            "",
            "All detectors operate on absolute residual magnitudes. A scenario is "
            "detected at the first alarm sample at or after its earliest configured "
            "campaign event. The baseline has no detection target.",
            "",
            "## Metric Notes",
            "",
            "- `false_positive_count` counts distinct alarm episodes before the "
            "first configured fault; for the baseline it covers the complete trace.",
            "- `missed_detection` is one only for a fault scenario with no offline "
            "alarm at or after the first configured fault start.",
            "- ECU DTC latency is extracted independently from the first non-`none` "
            "DTC at or after the same fault start.",
            "- Calibration-memory corruption is not directly represented by the "
            "three residual inputs, so a miss is an informative limitation of this "
            "initial detector set.",
            "",
            "## Scenario Results",
            "",
            "| Scenario | Algorithm | Fault type | Detected | Latency [s] | ECU DTC | ECU latency [s] | False positives |",
            "|---|---|---|---:|---:|---|---:|---:|",
        ]
    )
    for result in results:
        lines.append(
            f"| {result['scenario_id']} | {result['algorithm']} | "
            f"{result['fault_type']} | {int(bool(result['detected']))} | "
            f"{format_optional_float(result['detection_latency_s'])} | "
            f"{result['first_ecu_dtc_label']} | "
            f"{format_optional_float(result['ecu_dtc_latency_s'])} | "
            f"{result['false_positive_count']} |"
        )
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def plot_figures(output_dir: Path, results: Sequence[Dict[str, object]]) -> List[Path]:
    os.environ.setdefault("MPLCONFIGDIR", "/tmp/virtual_ecu_mpl")
    os.makedirs(os.environ["MPLCONFIGDIR"], exist_ok=True)
    try:
        import matplotlib

        matplotlib.use("Agg")
        import matplotlib.pyplot as plt
    except ImportError:
        print("Matplotlib is not installed; skipping optional figures.")
        return []

    figures_dir = output_dir / "figures"
    figures_dir.mkdir(parents=True, exist_ok=True)
    colors = {
        "threshold": "#4c78a8",
        "ewma": "#e6a141",
        "cusum": "#4c9f70",
    }
    fault_scenarios = [item for item in SCENARIO_IDS if item != "baseline"]
    short_labels = [
        "fan stuck",
        "pump degraded",
        "stale sensor",
        "sensor bias",
        "calibration",
        "multi-fault",
    ]

    fig, ax = plt.subplots(figsize=(10.0, 5.2), constrained_layout=True)
    width = 0.24
    offsets = [-width, 0.0, width]
    by_key = {
        (str(row["scenario_id"]), str(row["algorithm"])): row for row in results
    }
    for algorithm, offset in zip(ALGORITHM_ORDER, offsets):
        positions = []
        latencies = []
        for index, scenario_id in enumerate(fault_scenarios):
            latency = by_key[(scenario_id, algorithm)]["detection_latency_s"]
            if latency is not None:
                positions.append(index + offset)
                latencies.append(float(latency))
        ax.bar(
            positions,
            latencies,
            width=width,
            label=algorithm,
            color=colors[algorithm],
        )
    ax.set_xticks(range(len(fault_scenarios)), short_labels, rotation=20, ha="right")
    ax.set_ylabel("Detection latency [s]")
    ax.set_title("Offline Detection Latency by Algorithm")
    ax.grid(axis="y", linestyle=":", linewidth=0.7, alpha=0.8)
    ax.legend(frameon=False)
    latency_path = figures_dir / "detection_latency_by_algorithm.png"
    fig.savefig(latency_path, dpi=200)
    plt.close(fig)

    metrics = algorithm_metrics(results)
    rates = [100.0 * float(metrics[name]["detection_rate"]) for name in ALGORITHM_ORDER]
    fig, ax = plt.subplots(figsize=(7.2, 4.6), constrained_layout=True)
    bars = ax.bar(
        ALGORITHM_ORDER,
        rates,
        color=[colors[name] for name in ALGORITHM_ORDER],
        width=0.62,
    )
    ax.set_ylim(0.0, 105.0)
    ax.set_ylabel("Fault scenarios detected [%]")
    ax.set_title("Offline Detection Rate by Algorithm")
    ax.grid(axis="y", linestyle=":", linewidth=0.7, alpha=0.8)
    for bar, rate in zip(bars, rates):
        ax.text(
            bar.get_x() + bar.get_width() / 2.0,
            rate + 2.0,
            f"{rate:.1f}%",
            ha="center",
            va="bottom",
        )
    rate_path = figures_dir / "detection_rate_by_algorithm.png"
    fig.savefig(rate_path, dpi=200)
    plt.close(fig)
    return [latency_path, rate_path]


def main() -> int:
    args = parse_args()
    input_dir = args.input_dir.resolve()
    output_dir = args.output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    results = run_study(input_dir)
    comparison_path = output_dir / "algorithm_comparison.csv"
    summary_path = output_dir / "detection_summary.md"
    write_comparison_csv(comparison_path, results)
    write_summary(summary_path, results)
    figures = [] if args.no_figures else plot_figures(output_dir, results)

    print(f"Wrote {comparison_path}")
    print(f"Wrote {summary_path}")
    for path in figures:
        print(f"Wrote {path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
