#ifndef CONFIG_H
#define CONFIG_H

#define ECU_DT_MS 100U
#define ECU_SIM_DURATION_MS 120000U
#define ECU_MIN_SIM_DURATION_MS 1000U
#define ECU_MAX_SIM_DURATION_MS 3600000U

#define ECU_SENSOR_PERIOD_MS 100U
#define ECU_COOLANT_SENSOR_FRESHNESS_STALE_MS (3U * ECU_SENSOR_PERIOD_MS)
#define ECU_CONTROL_PERIOD_MS 100U
#define ECU_ACTUATOR_PERIOD_MS 100U
#define ECU_FAN_ACTUATOR_COMMAND_ACTIVE_MIN 0.05f
#define ECU_FAN_ACTUATOR_RESPONSE_GAP 0.20f
#define ECU_FAN_ACTUATOR_HEALTH_FAULT_SCORE 1.00f
#define ECU_DIAGNOSTIC_PERIOD_MS 500U
#define ECU_SAFETY_PERIOD_MS 100U
#define ECU_LOG_PERIOD_MS 100U

#define ECU_MAX_FAULT_EVENTS 4U
#define ECU_MAX_DRIVING_PROFILE_SEGMENTS 16U
#define ECU_PATH_BUFFER_SIZE 512U

#define ECU_DEFAULT_LOG_PATH "logs/thermal_run.csv"

#define ECU_TARGET_COOLANT_TEMP_C 92.0f
#define ECU_WARN_COOLANT_TEMP_C 108.0f
#define ECU_CRITICAL_COOLANT_TEMP_C 115.0f
#define ECU_SHUTDOWN_COOLANT_TEMP_C 118.0f
#define ECU_SENSOR_IMPLAUSIBLE_LOW_C -40.0f
#define ECU_SENSOR_IMPLAUSIBLE_HIGH_C 150.0f
#define ECU_SENSOR_RATIONALITY_RESIDUAL_C 4.0f

#define ECU_DTC_CONFIRM_COUNT 2U
#define ECU_DTC_PERMANENT_COUNT 5U
#define ECU_DTC_CLEAR_COUNT 4U

#define ECU_SAFE_STATE_RECOVERY_COUNT 20U

#define ECU_PRECAUTIONARY_LOAD_SCALE 1.00f
#define ECU_LIMP_HOME_LOAD_SCALE 0.70f
#define ECU_CONTROLLED_SHUTDOWN_LOAD_SCALE 0.25f

#endif
