#ifndef CONFIG_H
#define CONFIG_H

#define ECU_DT_MS 100U
#define ECU_SIM_DURATION_MS 120000U

#define ECU_SENSOR_PERIOD_MS 100U
#define ECU_CONTROL_PERIOD_MS 100U
#define ECU_ACTUATOR_PERIOD_MS 100U
#define ECU_DIAGNOSTIC_PERIOD_MS 500U
#define ECU_SAFETY_PERIOD_MS 100U
#define ECU_LOG_PERIOD_MS 100U

#define ECU_DEFAULT_LOG_PATH "logs/thermal_run.csv"

#define ECU_TARGET_COOLANT_TEMP_C 92.0f
#define ECU_WARN_COOLANT_TEMP_C 108.0f
#define ECU_CRITICAL_COOLANT_TEMP_C 115.0f
#define ECU_SENSOR_IMPLAUSIBLE_LOW_C -40.0f
#define ECU_SENSOR_IMPLAUSIBLE_HIGH_C 150.0f

#endif
